schema_version: 1

context:
  name: dtool_lookup_server_retrieve_plugin_mongo
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/dtool-lookup-server-retrieve-plugin-mongo/dtool-lookup-server-retrieve-plugin-mongo-${{ version }}.tar.gz
  sha256: 83c7aba1f7d24c335672165f48220c3c644073c985ffa6e6096af48579fff3bf

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pymongo
    - dtoolcore >=3.18.0
    - dtool_lookup_server

tests:
  - python:
      imports:
        - dtool_lookup_server_retrieve_plugin_mongo
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Retrieve plugin for dtool-lookup-server using mongodb
  license: MIT
  license_file: LICENSE.rst
  homepage: https://github.com/jic-dtool/dtool-lookup-server-retrieve-plugin-mongo

extra:
  recipe-maintainers:
    - jan-janssen
